In [ ]:
import nltk
nltk.download("brown")
import gensim
# Load the binary model

In [1]:
import gensim
# Load the binary model
model = gensim.models.KeyedVectors.load_word2vec_format("models/GoogleNews-vectors-negative300.bin.gz", binary = True)
# model.save_word2vec_format('models/GoogleNews-vectors-negative300.txt', binary=False)

In [2]:


# Only output word that appear in the Brown corpus
from nltk.corpus import brown
words = set(brown.words())
print(len(words))

# Output presented word to a temporary file
out_file = "models/pruned.word2vec.txt"
with open(out_file,"w") as f:
    word_presented = words.intersection(model.index_to_key)
    f.write("{} {}\n".format(len(word_presented),len(model["word"])))

    for word in word_presented:
        f.write("{} {}\n".format(word, " ".join(str(value) for value in model[word])))

56057


In [3]:
from nltk.corpus import words
words = set(words.words())
print(len(words))

# Output presented word to a temporary file
out_file = "models/english.word2vec.txt"
with open(out_file,"w") as f:
    word_presented = words.intersection(model.index_to_key)
    f.write("{} {}\n".format(len(word_presented),len(model["word"])))

    for word in word_presented:
        f.write("{} {}\n".format(word, " ".join(str(value) for value in model[word])))

235892


In [1]:
import gensim
# Load the binary model
model = gensim.models.KeyedVectors.load_word2vec_format("models/pruned.word2vec.txt", binary=False)
model.save_word2vec_format("models/pruned.word2vec.bin", binary=True)

In [2]:
model.save_word2vec_format("models/english.word2vec.bin", binary=True)

In [2]:
model["university"]

array([-1.52343750e-01, -1.16699219e-01,  1.70898438e-01,  2.89062500e-01,
        2.69531250e-01, -8.59375000e-02,  1.69921875e-01, -1.23046875e-01,
       -3.11279297e-02, -1.87500000e-01,  1.22070312e-01, -1.29882812e-01,
        3.19824219e-02,  7.76367188e-02, -2.17773438e-01,  1.10473633e-02,
       -2.09960938e-01, -7.66601562e-02,  1.87500000e-01, -1.33789062e-01,
       -7.81250000e-03,  1.70898438e-01,  4.83398438e-02, -3.38745117e-03,
        4.85229492e-03, -2.14843750e-01, -1.48437500e-01,  3.19824219e-02,
       -1.18164062e-01,  6.73828125e-02,  1.32812500e-01, -8.93554688e-02,
       -5.76171875e-02, -5.68847656e-02,  8.10546875e-02, -2.08984375e-01,
        5.81054688e-02,  9.37500000e-02, -6.39648438e-02,  1.44531250e-01,
       -9.91210938e-02,  5.20019531e-02, -8.25195312e-02,  3.85742188e-02,
       -6.34765625e-02, -1.00585938e-01,  3.12500000e-02, -1.15234375e-01,
       -2.73437500e-01,  3.21960449e-03,  9.76562500e-02, -1.96289062e-01,
        1.71875000e-01,  

In [3]:
len(model["word"])

300

In [4]:
model["universities"]

array([-7.81250000e-02, -3.50952148e-04,  2.41210938e-01,  4.74609375e-01,
        2.32421875e-01, -3.46679688e-02, -9.61914062e-02,  6.25000000e-02,
        1.25000000e-01, -1.89453125e-01,  1.11328125e-01, -1.30859375e-01,
       -1.04492188e-01,  1.83593750e-01, -2.57812500e-01,  1.33789062e-01,
       -2.20703125e-01, -2.34375000e-02,  1.43554688e-01, -1.72853470e-05,
        4.24804688e-02,  2.61718750e-01, -1.15871429e-04, -3.22265625e-02,
       -9.64355469e-03, -1.53320312e-01, -1.35742188e-01, -2.41210938e-01,
       -1.04003906e-01,  4.73632812e-02,  1.45507812e-01, -2.28271484e-02,
        2.42919922e-02, -2.27050781e-02,  2.00195312e-01, -3.02734375e-01,
       -1.70898438e-02,  1.95312500e-01, -1.46484375e-01,  4.04296875e-01,
        8.83789062e-02,  2.01416016e-02, -6.12792969e-02,  5.02929688e-02,
        3.04687500e-01, -1.88476562e-01,  1.03027344e-01, -5.27343750e-02,
       -3.22265625e-01, -1.36108398e-02,  1.04980469e-01, -9.33837891e-03,
       -2.00195312e-02,  

In [8]:
import numpy as np
model.cosine_similarities(model['cat'], np.array([model['university']]))

array([0.04555676], dtype=float32)

In [9]:
model.most_similar(positive=['treasure'], topn = 3)

[('treasures', 0.7821186780929565),
 ('treasured', 0.5532426834106445),
 ('jewels', 0.5178673267364502)]